name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    name: PHPCS / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1','8.2','8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: none

      - name: Install dependencies (no-scripts)
        run: composer install --no-interaction --no-progress --no-scripts

      - name: PHP Version
        run: php -v

      - name: Run PHPCS (WPCS)
        run: vendor/bin/phpcs -q

  lint_js_css:
    name: Lint JS/CSS (Node LTS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Node deps
        run: |
          npm ci || npm install

      - name: Lint JS
        run: npm run -s lint:js

      - name: Lint CSS
        run: npm run -s lint:css
